accounts/urls.py
from django.urls import path

from .views import LoginView, LogoutView, ProfileUpdateView, SignupView, profile

app_name = "accounts"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", profile, name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile_edit"),
]

config/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed("debug_toolbar"):
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [path("", TemplateView.as_view(template_name="root.html"), name="root")]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True)

accounts/forms.py
import os

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.core.files import File
from django.core.files.base import ContentFile
from django.forms import ModelForm
from PIL import Image

from accounts.models import Profile, User


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ("email",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if email:
            user_qs = User.objects.filter(email__iexact=email)
            if user_qs.exists():
                raise ValidationError("이미 등록된 이메일 주소입니다.")
        return email

    helper = FormHelper()
    helper.attrs = {"novalidate": True}
    helper.layout = Layout("username", "email", "password1", "password2")
    helper.add_input(Submit("submit", "회원가입", css_class="w-100"))


class LoginForm(AuthenticationForm):
    helper = FormHelper()
    helper.attrs = {"novalidate": True}
    helper.layout = Layout("username", "password")
    helper.add_input(Submit("submit", "로그인", css_class="w-100"))


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar"]

    helper = FormHelper()
    helper.attrs = {"novalidate": True}
    helper.layout = Layout("avatar")
    helper.add_input(Submit("submit", "저장", css_class="w-100"))

    def clean_avatar(self):
        avatar_file: File = self.cleaned_data.get("avatar")
        if avatar_file:
            img = Image.open(avatar_file)
            MAX_SIZE = (512, 512)
            img.thumbnail(MAX_SIZE)
            img = img.convert("RGB")

            thumb_name = os.path.splitext(avatar_file.name)[0] + ".jpg"
            thumb_file = ContentFile(b"", name=thumb_name)
            img.save(thumb_file, format="jpeg")

            return thumb_file

        return avatar_file

accounts/views.py
from typing import Optional

from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.contrib.auth.views import LogoutView as DjangoLogoutView
from django.contrib.auth.views import RedirectURLMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from accounts.forms import LoginForm, ProfileForm, SignupForm
from accounts.models import Profile, User
from accounts.utils import send_welcome_email


class SignupView(RedirectURLMixin, CreateView):
    model = User
    form_class = SignupForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "회원가입"}
    success_url = reverse_lazy("accounts:profile")

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            redirect_to = self.success_url
            if redirect_to != request.path:
                messages.warning(request, "로그인 유저는 회원가입할 수 없습니다.")
                return HttpResponseRedirect(redirect_to)
        response = super().dispatch(request, *args, **kwargs)
        return response

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "회원가입을 환영합니다. ;-)")

        user = self.object
        auth_login(self.request, user)
        messages.success(self.request, "회원가입과 동시에 로그인 지원 !")
        send_welcome_email(user, fail_silently=True)

        return response


class LoginView(DjangoLoginView):
    redirect_authenticated_user = True
    form_class = LoginForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "로그인"}


class LogoutView(DjangoLogoutView):
    next_page = "accounts:login"

    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.success(request, "로그아웃했습니다. :-)")
        return response


@login_required
def profile(request):
    return render(request, "accounts/profile.html")


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "프로필 수정"}
    success_url = reverse_lazy("accounts:profile")

    def get_object(self, queryset=None) -> Optional[Profile]:
        if not self.request.user.is_authenticated:
            return None

        try:
            return self.request.user.profile
        except Profile.DoesNotExist:
            return None

    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "프로필을 저장했습니다.")
        return response

accounts/templates/accounts/base.html
{% extends "base.html" %}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% block content %}
    <h2>{{ user.username }}'s 프로필</h2>

    {% if user.profile.avatar %}
        <img src="{{ user.profile.avatar.url }}"
             alt="{{ user }}'s avatar"
             class="rounded-circle img-fluid"
             style="max-width: 25%;"
        />
    {% endif %}

    <hr />
    <a href="{% url 'accounts:profile_edit' %}">프로필 수정</a>

{% endblock %}

core/templates/_crispy_form.html
{% load crispy_forms_tags %}

<div class="row py-5">
    <div class="col-sm-8 offset-sm-2">
        <div class="card">
            {% if form_title %}
                <div class="card-header">
                    {{ form_title }}
                </div>
            {% endif %}
            <div class="card-body">
                {% if form.helper %}
                    {% crispy form form.helper %}
                {% else %}
                    {% crispy form %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

core/templates/_messages_as_event.html
{% if messages %}
    {% for message in messages %}
        <script>
          (function () {
            const tag = "{{ message.level_tag }}";
            const message = "{{ message }}"
            /* body 요소에 toast-message 이벤트를 보냅니다. */
            htmx.trigger(document.body, 'toast-message', {message: message, tag: tag});
          })();
        </script>
    {% endfor %}
{% endif %}

core/templates/base.html
{% load component_tags static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>장고 프로젝트</title>
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}" />
    {% component_css_dependencies %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
            장고 프로젝트
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
            <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
            {% if not user.is_authenticated %}
            {% url 'accounts:login' as login_url %}
            <a href="{{ login_url }}{% if login_url != request.path %}?next={{ request.path }}{% endif %}"
               class="btn btn-outline-light me-2">로그인</a>
            <a href="{% url 'accounts:signup' %}?next={{ request.path }}"
               class="btn btn-warning">회원가입</a>
        {% else %}
            <a href="{% url 'accounts:profile' %}"
               class="btn btn-outline-light me-2">프로필</a>
            <a hx-post="{% url 'accounts:logout' %}?next={{ request.path }}"
               hx-target="body"
               hx-push-url="true"
               class="btn btn-warning">로그아웃</a>
            {% endif %}
        </div>
        </div>
    </div>
</header>

<main class="py-5">
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        &copy; 파이썬 사랑방
    </div>
</footer>

{% if debug %}
    <script src="{% static 'htmx/1.9.12/htmx.js' %}"></script>
{% else %}
    <script src="{% static 'htmx/1.9.12/htmx.min.js' %}"></script>
{% endif %}
<script src="{% static 'bootstrap/5.3.3/js/bootstrap.min.js' %}"></script>
{% component_js_dependencies %}
<script src="{% static 'htmx/ext/hx-get-with-timestamp.js' %}"></script>
<script src="{% static "toast-messages.js" %}"></script>

{% include "_messages_as_event.html" %}


</body>
</html>

core/templates/crispy_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "_crispy_form.html" with form=form form_title=form_title %}
{% endblock %}

core/templates/root.html
{% extends "base.html" %}
{% load component_tags %}

{% block content %}
    root.html

    {# {% component "modal-form" %}{% endcomponent %} #}
{% endblock %}